version: '3.7'
services:
  redis-refresh-token:
    image: redis:alpine
    command: redis-server /usr/local/etc/redis-refresh-token/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./data/refresh-token-data:/data
      - ./data/refresh-token-data/redis.conf:/usr/local/etc/redis-refresh-token/redis.conf
